### ISSUE TITLE
Somnia seems to be broken on v1.18.2

### ISSUE THREAD

**Issue by 5ynth** [Su5eD/Somnia-Awoken#106]
### Describe the bug

When Somnia is added to mods list, game will no longer launch

### Is this bug related to another mod?

no 

### Steps to reproduce

1.Install library mod, and Somnia
2.Launch Game

### Expected Behavior

Game instance will Code 1 immediately.

### Additional context

Installed mod on GDlauncher

Error Msgs in console:
actions.js:3286 ps stderr: Exception in thread "main" 
(anonymous) @ actions.js:3286
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
actions.js:3286 ps stderr: java.lang.RuntimeException: Source location of namespace 'somnia' doesn't match the location of its mod

(anonymous) @ actions.js:3286
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
actions.js:3286 ps stderr: 	at wtf.gofancy.koremods.service.ModlauncherKoremodsLaunchPlugin.verifyScriptPacks$koremods_modlauncher(ModlauncherKoremodsLaunchPlugin.kt:68)
	at wtf.gofancy.koremods.service.KoremodsTransformationService.completeScan(KoremodsTransformationService.kt:56)

(anonymous) @ actions.js:3286
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
actions.js:3286 ps stderr: 	at LAYER SERVICE/koremods.modlauncher@0.4.10/wtf.gofancy.koremods.service.KoremodsServiceWrapper.completeScan(KoremodsServiceWrapper.java:91)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:174)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$23(TransformationServicesHandler.java:142)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)

(anonymous) @ actions.js:3286
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
actions.js:3286 ps stderr: 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.triggerScanCompletion(TransformationServicesHandler.java:144)

(anonymous) @ actions.js:3286
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
actions.js:3286 ps stderr: 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:94)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by Su5eD** [comment]
Fixed in Koremods-Modlauncher `0.4.11`.
