### ISSUE TITLE
The game crashes with a white screen when opening Volex Map MiniMap Menu

### ISSUE THREAD

**Issue by Accidey** [Su5eD/Somnia-Awoken#70]
### Describe the bug

The game crashes with a white screen when opening Volex Map

### Is this bug related to another mod?

Y

### Steps to reproduce

1.When the Volex Map minimap is opened for the first time, the game will be blank and then crash directly
2.java.util.ConcurrentModificationException
    at java.util.ArrayList.forEach(Unknown Source)
    at meldexun.entityculling.renderer.tileentity.TileEntityRenderer.fillTileEntityLists(TileEntityRenderer.java:41)
    at meldexun.entityculling.renderer.tileentity.TileEntityRendererOptifine.fillTileEntityLists(TileEntityRendererOptifine.java:32)
    at meldexun.entityculling.renderer.tileentity.TileEntityRenderer.setup(TileEntityRenderer.java:31)
    at meldexun.entityculling.renderer.tileentity.TileEntityRendererOptifine.setup(TileEntityRendererOptifine.java:21)
    at meldexun.entityculling.asm.hook.RenderGlobalHook.setup(RenderGlobalHook.java:35)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java)
    at net.optifine.shaders.ShadersRender.setupTerrain(ShadersRender.java:58)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1735)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
    at com.kingrunes.somnia.common.util.SomniaUtil.renderWorld(SomniaUtil.java:75)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
3.
...

**Comment by Accidey** [comment]
The version is 1.11-beta2，This problem happens occasionally，I hope you can help me

**Comment by Su5eD** [comment]
Does this also happen without Optifine or Entity Culling?

**Comment by Accidey** [comment]
I added EntityCulling Mod, maybe the reason for the crash is this. Only Somnia and Volex Map will not crash

**Comment by Su5eD** [comment]
Looks like an issue with EntityCulling then, please report it on their repo.
